os: linux
dist: bionic
language: python
python: "3.6"

env:
    - DOCKER_CLI_EXPERIMENTAL=enabled MY_VER="" ORIG_VER="" ORIG_NAME=adferrand/letsencrypt-dns IMAGE_NAME=patrickpissurno/rpi-docker-letsencrypt-dns REGISTRY_USER=patrickpissurno # REGISTRY_PASS=...
    
before_script:
    - sudo apt-get install manpages-posix
    - ORIG_VER="$(./get_latest.sh $ORIG_NAME)"
    - MY_VER="$(./get_latest.sh $IMAGE_NAME)"
    - if [ -n "$MY_VER" ] && [ "$MY_VER" = "$ORIG_VER" ]; then travis_terminate 0; fi
    - pip3 install travis-wait-improved
    - curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
    - docker --version
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - df -h
    
script:
    - git clone https://github.com/adferrand/docker-letsencrypt-dns.git build && cd build
    - if [ -f VERSION ]; then TAG="--tag $IMAGE_NAME:$(cat VERSION)"; fi
    - travis-wait-improved --timeout 240m docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 $TAG --tag "${IMAGE_NAME}" --push .
