os: linux
# dist: xenial
dist: bionic

services:
    - docker

addons:
    apt:
        packages:
        - docker-ce

env:
    - DOCKER_CLI_EXPERIMENTAL=enabled IMAGE_NAME=patrickpissurno/rpi-docker-letsencrypt-dns REGISTRY_USER=patrickpissurno # REGISTRY_PASS=...
    
before_script:
    - sudo apt update
    - sudo apt upgrade
    - sudo wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
    - docker --version
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
    - docker buildx create --use
    
script:
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 --tag "${IMAGE_NAME}:latest" --push .

