os: linux
dist: bionic
language: minimal

env:
    - DOCKER_CLI_EXPERIMENTAL=enabled ORIG_NAME=adferrand/letsencrypt-dns IMAGE_NAME=patrickpissurno/rpi-docker-letsencrypt-dns REGISTRY_USER=patrickpissurno # REGISTRY_PASS=...
    
before_script:
    - sudo apt-get install manpages-posix
    - |
      ORIG_VER2="$(wget -q https://registry.hub.docker.com/v1/repositories/$ORIG_NAME/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | sort -V | tail -n2)"
      for i in $ORIG_VER2; do [ "$i" != "latest" ] && ORIG_VER="$i"; done
      MY_VER2="$(wget -q https://registry.hub.docker.com/v1/repositories/$IMAGE_NAME/tags -O -  | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | sort -V | tail -n2)"
      for i in $MY_VER2; do [ "$i" != "latest" ] && MY_VER="$i"; done
      echo "$ORIG_NAME Version $ORIG_VER"
      echo "$IMAGE_NAME Version $MY_VER"
      if [ -z "$NOW" ] && [ -n "$MY_VER" ] && [ "$MY_VER" = "$ORIG_VER" ]; then travis_terminate 0; fi
    - curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
    - docker --version
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - df -h
    
script:
    - git clone https://github.com/adferrand/docker-letsencrypt-dns.git build && cd build
    - patch -i ../10-use-py3-packages.patch
    - sed -i s+/usr/local/bin/circusd+/usr/bin/circusd+g files/run.sh
    - if [ -n "$ORIG_VER" ]; then TAG="--tag $IMAGE_NAME:$ORIG_VER"
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 $TAG --tag "${IMAGE_NAME}" --push .
