os: linux
# dist: xenial
dist: bionic

# services:
#     - docker

# addons:
#     apt:
#         packages:
#         - docker-ce

env:
    - DOCKER_CLI_EXPERIMENTAL=enabled IMAGE_NAME=patrickpissurno/rpi-docker-letsencrypt-dns REGISTRY_USER=patrickpissurno # REGISTRY_PASS=...
    
before_script:
    # - docker --version
    - sudo apt update
    - sudo apt upgrade -y
    - curl -fsSL test.docker.com -o get-docker.sh && sh get-docker.sh
    - sudo usermod -aG docker $USER
    - sudo docker --version
    - sudo docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
    - sudo docker buildx create --use
    
script:
    - sudo docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 --tag "${IMAGE_NAME}:latest" --push .

